version: '3.4'

services:
  botlog.api:
    image: ${DOCKER_REGISTRY-}botlog
    build:
      context: .
      dockerfile: BotLog.API/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=someRandomPa$$w0rd
      - ACCEPT_EULA=Y

  rabbitmq:
    image: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"